local cuda_root = "/usr/local/cuda-12.4"

target("llaisys-device-nvidia")
    set_kind("static")
    add_rules("cuda")
    set_values("cuda.rdc", false)
    set_languages("cxx17")
    add_includedirs(path.join(cuda_root, "include"), {public = true})
    add_linkdirs(path.join(cuda_root, "lib64"), {public = true})
    add_links("cudart", {public = true})
    add_cuflags("-arch=sm_80", "--expt-relaxed-constexpr", "-Xcompiler=-fPIC")
    add_files("../src/device/nvidia/*.cu")
    on_install(function (target) end)
target_end()

target("llaisys-ops-nvidia")
    set_kind("static")
    add_rules("cuda")
    set_values("cuda.rdc", false)
    add_deps("llaisys-tensor", "llaisys-device-nvidia")
    set_languages("cxx17")
    add_includedirs(path.join(cuda_root, "include"), {public = true})
    add_linkdirs(path.join(cuda_root, "lib64"), {public = true})
    add_links("cudart", "cublas", {public = true})
    add_cuflags("-arch=sm_80", "--expt-relaxed-constexpr", "-Xcompiler=-fPIC")
    add_files("../src/ops/*/nvidia/*.cu")
    on_install(function (target) end)
target_end()
